name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          IMAGE_NAME=my-image-name:$(date +%s)
          docker build . --file Dockerfile --tag $IMAGE_NAME
          echo "::set-output name=image_name::$IMAGE_NAME"
        id: build_image

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1